# Generated by Django 2.2.6 on 2019-10-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdh_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinfo',
            options={'verbose_name_plural': 'CustomersInfo'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='date_added',
            new_name='date_joined',
        ),
    ]
